stages:
  - build-angular
  - build-nupkg
  - push

build-angular:
  stage: build-angular
  image: node:16-alpine
  before_script:
    - cd mcms-forms-ng
    - yarn
  script:
    - yarn build:form
  artifacts:
    paths:
      - mcms-forms-ng/dist/mcms-form
    expire_in: 1 days
  cache:
    paths:
      - mcms-forms-ng/node_modules
  only:
    - /^publish-.*$/

build-nupkg:
  stage: build-nupkg
  image: mcr.microsoft.com/dotnet/sdk:5.0
  needs:
    - build-angular
  script:
    - cd MCMS.Forms
    - ./copy-js.sh $CI_COMMIT_TAG
    - ./pack.sh $CI_COMMIT_TAG
  artifacts:
    paths:
      - MCMS.Forms/nuget-build
  only:
    - /^publish-.*$/

gitlab-registry-push:
  stage: push
  image: mcr.microsoft.com/dotnet/sdk:5.0
  needs:
    - build-nupkg
  variables:
    GIT_STRATEGY: none
  script:
    - dotnet nuget list source | grep "TDRs GitLab" && dotnet nuget remove source "TDRs GitLab"
    - dotnet nuget add source "https://nuget.tdrs.ro/index.json" --name "TDRs GitLab" --username gitlab-ci-token --password $CI_JOB_TOKEN --store-password-in-clear-text
    - cd MCMS.Forms
    - dotnet nuget push "./nuget-build/*.nupkg" "./nuget-build/*.snupkg" --source "TDRs GitLab"
  only:
    - /^publish-.*$/

nuget-push:
  stage: push
  image: mcr.microsoft.com/dotnet/sdk:5.0
  variables:
    GIT_STRATEGY: none
  needs:
    - build-nupkg
  script:
    - cd MCMS.Forms
    - dotnet nuget push "./nuget-build/*.nupkg" "./nuget-build/*.snupkg" --api-key "$NUGET_API_KEY" --source https://api.nuget.org/v3/index.json --skip-duplicate
  only:
    - /^publish-.*$/
  when: manual
