stages:
  - build-angular
  - build-nupkg
  - nuget-push

build-angular:
  stage: build-angular
  image: node:14-alpine
  before_script:
    - cd mcms-forms-ng
    - npm i
  script:
    - npm run build:form
  artifacts:
    paths:
      - mcms-forms-ng/dist/mcms-form
    expire_in: 1 days
  cache:
    paths:
      - mcms-forms-ng/node_modules
  only:
    - /^publish-.*$/

build-nupkg:
  stage: build-nupkg
  image: mcr.microsoft.com/dotnet/sdk:5.0
  script:
    - cd MCMS.Forms
    - ./copy-js.sh $CI_COMMIT_TAG
    - ./pack.sh $CI_COMMIT_TAG
  artifacts:
    paths:
      - MCMS.Forms/nuget-build
  only:
    - /^publish-.*$/

nuget-push:
  stage: nuget-push
  image: mcr.microsoft.com/dotnet/sdk:5.0
  script:
    - cd MCMS.Forms/nuget-build
    - dotnet nuget add source "$CI_SERVER_URL/api/v4/projects/$CI_PROJECT_ID/packages/nuget/index.json" --name gitlab --username gitlab-ci-token --password $CI_JOB_TOKEN --store-password-in-clear-text
    - dotnet nuget push "*.nupkg" "*.snupkg" --source gitlab
  only:
    - /^publish-.*$/